### ISSUE TITLE
Console gets stuck when deleting a tab

### ISSUE THREAD

**Issue by eismail-aiopsgroup** [z1haze/sfcc_dev_console#1]
Hi @z1haze,

The console gets stuck when a tab is deleted. After deleting the tab, I would expect that the previous or a new tab is automatically opened. But instead, a blank editor is shown and the entire page/tab becomes completely unresponsive:
![image](https://user-images.githubusercontent.com/80893079/216573799-a239fda0-0de3-43e7-a4fc-607f9b350812.png)

Also, the page cannot be refreshed anymore, it just "loads" forever until the browser offers you to force-close the tab.

Error in Chrome Dev Tools:
![image](https://user-images.githubusercontent.com/80893079/216575145-75e1bcc0-eff6-4c76-bd01-c45a9bfd7d3b.png)

Opening a new console in a new tab works fine and the previously deleted tab is gone as expected.

Browser: Chrome Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by z1haze** [comment]
Hi @eismail-aiopsgroup,

Sorry about this. I have not had access to a sandbox to thoroughly test my recent changes. I have instead been relying on others to test things for me. I now have the access I need to test the cartridge, and I have already replicated your issue. I will work on a fix for today. Thank you for bringing this up.

**Comment by z1haze** [comment]
@eismail-aiopsgroup, there were a slew of updates following this commit. I _think_ im done updating at the moment, everything appears to be working on my end. Please let me know if when on version 2.0.6 or later, you are still having these issues

**Comment by eismail-aiopsgroup** [comment]
Hi @z1haze,

I can confirm the issue with the tabs is fixed now. The confirmation popup is also very useful against accidental clicks. Thanks!

The only problem I noticed in v2.2.0 (https://github.com/z1haze/sfcc_dev_console/blob/master/cartridges/sfcc_dev_console/cartridge/controllers/Console.js #90) is that you are using an arrow function which is not supported by older compatibility versions. After replacing it with a regular function syntax, the logging itself works perfectly though.

**Comment by z1haze** [comment]
Oops, sorry about that -- I often forget that some sites are still on very old compatibility. I can switch that back to a traditional function to maintain backwards compatibility.
