### ISSUE TITLE
Storefront Documentation ?

### ISSUE THREAD

**Issue by jakvike** [z1haze/sfcc_dev_console#6]
Not able to run Storefront Console.  Documentation says to follow Storefront Installation. However, I do not see where the documentation is located.

**Comment by jakvike** [comment]
I am able to click on the Console(storefront) link in BM. It opens up the same conolse as Concole(BM).

**Comment by z1haze** [comment]
Please make sure you've followed all steps in the readme, beginning at https://github.com/z1haze/sfcc_dev_console#business-manager - Do do you have the cartridge in both the storefront and the bm cartridge path?

**Comment by jakvike** [comment]
Yes, it is in both cartridge paths.  The odd issue is the link to the console are opening the same console.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by z1haze** [comment]
I'm not really certain, as the link for storefront should be sending you to `ShowStorefront` controller endpoint which gets the current site. I am happy to help you troubleshoot this further on slack in sfcc-unofficial if you want to message me there.

p.s. you can try toggling code versions, that sometimes refreshes things in the system.
